/** Preset niches → Google Maps search phrases (keyword leg of “keyword + location”). */
export type NichePreset = {
  id: string;
  label: string;
  description: string;
  keywords: string[];
};

export const NICHE_PRESETS: NichePreset[] = [
  {
    id: "medical",
    label: "Medical & pharma distribution",
    description: "Distributors, surgical suppliers, hospital equipment",
    keywords: [
      "medical distributor",
      "pharma distributor",
      "surgical supplier",
      "hospital equipment supplier",
      "medical wholesaler",
    ],
  },
  {
    id: "dental",
    label: "Dental & oral surgery supply",
    description: "Dental labs, implant suppliers, chairside equipment",
    keywords: ["dental supply distributor", "dental equipment supplier", "orthodontic supplier", "dental lab"],
  },
  {
    id: "veterinary",
    label: "Veterinary & animal health",
    description: "Clinic suppliers, feed, pharma for vets",
    keywords: ["veterinary supply distributor", "animal health distributor", "veterinary equipment supplier"],
  },
  {
    id: "legal",
    label: "Legal & professional services",
    description: "Firms and B2B legal support (Maps discovery)",
    keywords: ["law firm", "legal services", "attorney office", "paralegal services"],
  },
  {
    id: "real_estate",
    label: "Real estate & property",
    description: "Brokerages, property management, commercial agents",
    keywords: ["real estate brokerage", "property management company", "commercial real estate agent"],
  },
  {
    id: "home_services",
    label: "Home services (trades)",
    description: "HVAC, plumbing, electrical, roofing",
    keywords: ["HVAC contractor", "plumbing company", "electrical contractor", "roofing contractor"],
  },
  {
    id: "construction",
    label: "Construction & contractors",
    description: "General contractors, builders, civil",
    keywords: ["general contractor", "construction company", "commercial builder", "civil contractor"],
  },
  {
    id: "automotive",
    label: "Automotive & fleet",
    description: "Dealers, parts, fleet repair",
    keywords: ["auto parts distributor", "fleet repair shop", "commercial truck dealer"],
  },
  {
    id: "food_service",
    label: "Food service & hospitality",
    description: "Restaurants, catering, supplies",
    keywords: ["restaurant supply distributor", "food service distributor", "catering company"],
  },
  {
    id: "industrial",
    label: "Industrial & manufacturing supply",
    description: "MRO, bearings, packaging, safety",
    keywords: ["industrial supply distributor", "MRO supplier", "packaging distributor", "safety equipment supplier"],
  },
  {
    id: "beauty",
    label: "Beauty & wellness B2B",
    description: "Salon distributors, spa supply",
    keywords: ["beauty supply distributor", "salon equipment supplier", "spa supply wholesale"],
  },
  {
    id: "fitness",
    label: "Fitness & recreation",
    description: "Gyms, studio equipment supply",
    keywords: ["gym equipment supplier", "fitness equipment distributor", "commercial gym supplier"],
  },
  {
    id: "custom",
    label: "Custom keywords (team entry)",
    description: "Enter your own phrases below",
    keywords: [],
  },
];

/** Regions / cities for the location leg of Maps search (add many for wider coverage). */
export const LOCATION_CATALOG: string[] = [
  // US — states & DC
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Washington DC",
  // US — major metros (optional finer targeting)
  "Houston TX",
  "Dallas TX",
  "Miami FL",
  "Los Angeles CA",
  "Chicago IL",
  "Phoenix AZ",
  "Philadelphia PA",
  "San Antonio TX",
  "San Diego CA",
  "Denver CO",
  "Seattle WA",
  "Atlanta GA",
  "Boston MA",
  "Detroit MI",
  // UK
  "London",
  "Birmingham",
  "Manchester",
  "Leeds",
  "Glasgow",
  "Liverpool",
  "Edinburgh",
  "Bristol",
  "Cardiff",
  "Belfast",
  // UAE & Gulf
  "Dubai",
  "Abu Dhabi",
  "Sharjah",
  "Riyadh",
  "Doha",
  // Canada
  "Ontario",
  "Quebec",
  "British Columbia",
  "Alberta",
  "Toronto",
  "Vancouver",
  "Montreal",
  "Calgary",
  // EU (country-level)
  "Germany",
  "France",
  "Netherlands",
  "Spain",
  "Italy",
  "Poland",
  "Ireland",
  "Sweden",
];
